apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: vproapp
spec:
  selector:
    app: vproapp
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
