apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproweb
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: vproweb
  template:
    metadata:
      labels:
        app: vproweb
    spec:
      containers:
        - name: vproweb
          image: {{ .Values.web.image }}
          ports:
            - containerPort: {{ .Values.web.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: vproweb
spec:
  selector:
    app: vproweb
  type: NodePort
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      nodePort: {{ .Values.web.nodePort }}
