db:
  image: your-dockerhub-username/vprofiledb:latest
  replicas: 1
  port: 3306
  rootPassword: ""

memcache:
  image: memcached
  replicas: 1
  port: 11211

rabbitmq:
  image: rabbitmq
  replicas: 1
  port: 5672

app:
<<<<<<< HEAD
  image: your-dockerhub-username/vprofileapp:latest
=======
  image: abroor/vprofileapp:44542da2a0901b62fafd4cb32f203f33a3938dde
>>>>>>> 09b504a7c02438b3835831d1d8b06943e2324340
  replicas: 1
  port: 8080

web:
  image: your-dockerhub-username/vprofileweb:latest
  replicas: 2
  port: 80
  nodePort: 30080
